In [1]:
!pip install opendatasets -q

In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import time
import pandas as pd
import opendatasets as od

In [3]:
od.download("https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents")

Skipping, found downloaded files in "./us-accidents" (use force=True to force download)

In [4]:
df = pd.read_csv("/content/us-accidents/US_Accidents_March23.csv",
                 nrows = 5000000
                 )

In [5]:
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 1.3+ GB

In [7]:
print(df.isnull().sum())

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  3402762
End_Lng                  3402762
Distance(mi)                   0
Description                    5
Street                      6593
City                         136
County                         0
State                          0
Zipcode                      844
Country                        0
Timezone                    4300
Airport_Code               12552
Weather_Timestamp          67442
Temperature(F)             94114
Wind_Chill(F)            1707907
Humidity(%)               100298
Pressure(in)               80673
Visibility(mi)            105610
Wind_Direction             96508
Wind_Speed(mph)           442145
Precipitation(in)        1840308
Weather_Condition         102683
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             13133
Civil_Twilight             13133
Nautical_Twilight          13133
Astronomical_Twilight      13133
dtype: int64

In [8]:
(df == 0).sum()

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                        0
End_Lng                        0
Distance(mi)             2919324
Description                    0
Street                         0
City                           0
County                         0
State                          0
Zipcode                        0
Country                        0
Timezone                       0
Airport_Code                   0
Weather_Timestamp              0
Temperature(F)              1610
Wind_Chill(F)               2284
Humidity(%)                    0
Pressure(in)                   2
Visibility(mi)              4445
Wind_Direction                 0
Wind_Speed(mph)           517322
Precipitation(in)        2809599
Weather_Condition              0
Amenity                  4933368
Bump                     4997853
Crossing                 4378051
Give_Way                 4972555
Junction                 4681995
No_Exit                  4986844
Railway                  4954971
Roundabout               4999829
Station                  4870729
Stop                     4852220
Traffic_Calming          4995033
Traffic_Signal           4119983
Turning_Loop             5000000
Sunrise_Sunset                 0
Civil_Twilight                 0
Nautical_Twilight              0
Astronomical_Twilight          0
dtype: int64

In [9]:
df_cleaned = df.dropna()

In [10]:
print("Cleaned Dataset Shape: ", df_cleaned.shape)

Cleaned Dataset Shape:  (1274636, 46)

In [15]:
print("\nRemaining Null Values:")
print(df_cleaned.isnull().sum())

Remaining Null Values:
ID                       0
Source                   0
Severity                 0
Start_Time               0
End_Time                 0
Start_Lat                0
Start_Lng                0
End_Lat                  0
End_Lng                  0
Distance(mi)             0
Description              0
Street                   0
City                     0
County                   0
State                    0
Zipcode                  0
Country                  0
Timezone                 0
Airport_Code             0
Weather_Timestamp        0
Temperature(F)           0
Wind_Chill(F)            0
Humidity(%)              0
Pressure(in)             0
Visibility(mi)           0
Wind_Direction           0
Wind_Speed(mph)          0
Precipitation(in)        0
Weather_Condition        0
Amenity                  0
Bump                     0
Crossing                 0
Give_Way                 0
Junction                 0
No_Exit                  0
Railway                  0
Roundabout               0
Station                  0
Stop                     0
Traffic_Calming          0
Traffic_Signal           0
Turning_Loop             0
Sunrise_Sunset           0
Civil_Twilight           0
Nautical_Twilight        0
Astronomical_Twilight    0
dtype: int64

In [17]:
df_cleaned.to_csv('/content/cleaned_dataset.csv', index=False)

In [18]:
features = [
    'ID',
    'Source',
    'Severity',
    'Start_Time',
    'End_Time',
    'Start_Lat',
    'Start_Lng',
    'Distance(mi)',
    'Street',
    'City',
    'County',
    'State',
    'Country',
    'Weather_Timestamp',
    'Temperature(F)',
    'Wind_Chill(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Direction',
    'Wind_Speed(mph)',
    'Precipitation(in)',
    'Weather_Condition',
    'Bump',
    'Crossing',
    'Give_Way',
    'Junction',
    'No_Exit',
    'Railway',
    'Roundabout',
    'Station',
    'Stop',
    'Traffic_Calming',
    'Traffic_Signal',
    'Turning_Loop',
    'Sunrise_Sunset'
]

In [26]:
df_final = df_cleaned[features]

In [27]:
output_file = "accident_final.csv"

In [29]:
df_final.to_csv(output_file, index= False)

In [30]:
df_final.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,City,...,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset
3402762,A-3412645,Source1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,3.230,Outerbelt E,Dublin,...,False,False,False,False,False,False,False,False,False,Night
3402767,A-3412650,Source1,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,0.500,I-75 S,Cincinnati,...,False,False,False,False,False,False,False,False,False,Day
3402771,A-3412654,Source1,2,2016-02-08 11:51:46,2016-02-08 17:51:46,41.375310,-81.820170,0.521,I-71 S,Cleveland,...,True,False,False,False,False,False,False,False,False,Day
3402773,A-3412656,Source1,2,2016-02-08 15:16:43,2016-02-08 21:16:43,40.109310,-82.968490,0.826,Outerbelt W,Westerville,...,False,False,False,False,False,False,False,False,False,Day
3402774,A-3412657,Source1,2,2016-02-08 15:43:50,2016-02-08 21:43:50,39.192880,-84.477230,0.307,I-75 N,Cincinnati,...,False,False,False,False,False,False,False,False,False,Day

In [31]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1274636 entries, 3402762 to 4999999
Data columns (total 36 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ID                 1274636 non-null  object
 1   Source             1274636 non-null  object
 2   Severity           1274636 non-null  int64
 3   Start_Time         1274636 non-null  object
 4   End_Time           1274636 non-null  object
 5   Start_Lat          1274636 non-null  float64
 6   Start_Lng          1274636 non-null  float64
 7   Distance(mi)       1274636 non-null  float64
 8   Street             1274636 non-null  object
 9   City               1274636 non-null  object
 10  County             1274636 non-null  object
 11  State              1274636 non-null  object
 12  Country            1274636 non-null  object
 13  Weather_Timestamp  1274636 non-null  object
 14  Temperature(F)     1274636 non-null  float64
 15  Wind_Chill(F)      1274636 non-null  float64
 16  Humidity(%)        1274636 non-null  float64
 17  Pressure(in)       1274636 non-null  float64
 18  Visibility(mi)     1274636 non-null  float64
 19  Wind_Direction     1274636 non-null  object
 20  Wind_Speed(mph)    1274636 non-null  float64
 21  Precipitation(in)  1274636 non-null  float64
 22  Weather_Condition  1274636 non-null  object
 23  Bump               1274636 non-null  bool
 24  Crossing           1274636 non-null  bool
 25  Give_Way           1274636 non-null  bool
 26  Junction           1274636 non-null  bool
 27  No_Exit            1274636 non-null  bool
 28  Railway            1274636 non-null  bool
 29  Roundabout         1274636 non-null  bool
 30  Station            1274636 non-null  bool
 31  Stop               1274636 non-null  bool
 32  Traffic_Calming    1274636 non-null  bool
 33  Traffic_Signal     1274636 non-null  bool
 34  Turning_Loop       1274636 non-null  bool
 35  Sunrise_Sunset     1274636 non-null  object
dtypes: bool(12), float64(10), int64(1), object(13)
memory usage: 257.7+ MB

In [32]:
print(df_final.isnull().sum())

ID                   0
Source               0
Severity             0
Start_Time           0
End_Time             0
Start_Lat            0
Start_Lng            0
Distance(mi)         0
Street               0
City                 0
County               0
State                0
Country              0
Weather_Timestamp    0
Temperature(F)       0
Wind_Chill(F)        0
Humidity(%)          0
Pressure(in)         0
Visibility(mi)       0
Wind_Direction       0
Wind_Speed(mph)      0
Precipitation(in)    0
Weather_Condition    0
Bump                 0
Crossing             0
Give_Way             0
Junction             0
No_Exit              0
Railway              0
Roundabout           0
Station              0
Stop                 0
Traffic_Calming      0
Traffic_Signal       0
Turning_Loop         0
Sunrise_Sunset       0
dtype: int64

In [33]:
(df_final == 0).sum()

ID                         0
Source                     0
Severity                   0
Start_Time                 0
End_Time                   0
Start_Lat                  0
Start_Lng                  0
Distance(mi)             533
Street                     0
City                       0
County                     0
State                      0
Country                    0
Weather_Timestamp          0
Temperature(F)           816
Wind_Chill(F)           1353
Humidity(%)                0
Pressure(in)               1
Visibility(mi)          1937
Wind_Direction             0
Wind_Speed(mph)       201874
Precipitation(in)    1175178
Weather_Condition          0
Bump                 1273864
Crossing             1161954
Give_Way             1270751
Junction             1186383
No_Exit              1271503
Railway              1265342
Roundabout           1274596
Station              1240153
Stop                 1241134
Traffic_Calming      1273240
Traffic_Signal       1177865
Turning_Loop         1274636
Sunrise_Sunset             0
dtype: int64

In [34]:
X_features = [
    'ID',
    'Source',
    'Start_Time',
    'End_Time',
    'Start_Lat',
    'Start_Lng',
    'Distance(mi)',
    'Street',
    'City',
    'County',
    'State',
    'Country',
    'Weather_Timestamp',
    'Temperature(F)',
    'Wind_Chill(F)',
    'Humidity(%)',
    'Pressure(in)',
    'Visibility(mi)',
    'Wind_Direction',
    'Wind_Speed(mph)',
    'Precipitation(in)',
    'Weather_Condition',
    'Bump',
    'Crossing',
    'Give_Way',
    'Junction',
    'No_Exit',
    'Railway',
    'Roundabout',
    'Station',
    'Stop',
    'Traffic_Calming',
    'Traffic_Signal',
    'Turning_Loop',
    'Sunrise_Sunset'
]

In [36]:
X = df_final[X_features]
y = df_final["Severity"]

In [39]:
X

,ID,Source,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,City,County,...,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset
3402762,A-3412645,Source1,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,3.230,Outerbelt E,Dublin,Franklin,...,False,False,False,False,False,False,False,False,False,Night
3402767,A-3412650,Source1,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,0.500,I-75 S,Cincinnati,Hamilton,...,False,False,False,False,False,False,False,False,False,Day
3402771,A-3412654,Source1,2016-02-08 11:51:46,2016-02-08 17:51:46,41.375310,-81.820170,0.521,I-71 S,Cleveland,Cuyahoga,...,True,False,False,False,False,False,False,False,False,Day
3402773,A-3412656,Source1,2016-02-08 15:16:43,2016-02-08 21:16:43,40.109310,-82.968490,0.826,Outerbelt W,Westerville,Franklin,...,False,False,False,False,False,False,False,False,False,Day
3402774,A-3412657,Source1,2016-02-08 15:43:50,2016-02-08 21:43:50,39.192880,-84.477230,0.307,I-75 N,Cincinnati,Hamilton,...,False,False,False,False,False,False,False,False,False,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,A-5037883,Source1,2022-11-09 16:09:00,2022-11-09 17:34:00,34.185388,-118.317917,3.099,I-5,Burbank,Los Angeles,...,False,False,False,False,False,False,False,False,False,Day
4999996,A-5037884,Source1,2022-07-24 19:19:50,2022-07-24 20:39:23,32.934967,-117.242523,0.026,Caminito San Marino,Del Mar,San Diego,...,False,False,False,False,False,False,False,False,False,Day
4999997,A-5037885,Source1,2023-01-18 15:55:30,2023-01-18 17:07:30,37.700654,-121.796602,9.134,I-580 E,Livermore,Alameda,...,False,False,False,False,False,False,False,False,False,Day
4999998,A-5037886,Source1,2022-10-13 14:22:30,2022-10-13 14:53:00,37.700647,-121.796590,1.456,I-580,Livermore,Alameda,...,False,False,False,False,False,False,False,False,False,Day
4999999,A-5037887,Source1,2022-04-16 17:26:16,2022-04-16 20:21:09,33.721994,-84.394682,1.182,University Ave SW,Atlanta,Fulton,...,False,False,False,False,False,False,False,False,False,Day

In [40]:
y

3402762    3
3402767    3
3402771    2
3402773    2
3402774    2
          ..
4999995    2
4999996    2
4999997    2
4999998    2
4999999    2
Name: Severity, Length: 1274636, dtype: int64